### ISSUE TITLE
Add support for Openstack / generic cloud

### ISSUE THREAD

**Issue by mariusleu** [AlmaLinux/cloud-images#12]
AlmaLinux needs to provide cloud images compatible with Openstack.

Basic requirements are
- qcow2 format (ready for libvirt)
- cloud-init with openstack datasource enabled

**Comment by CrucialDrew** [comment]
This is the reason I'm hesitant to offer it to VPS customers. Every major distro offers this. They aren't just useful for OpenStack either, because other clouds can add their cloud-init datasource to the cloud image.

Anything like these would be great: https://docs.openstack.org/image-guide/obtain-images.html

**Comment by ezamriy** [comment]
Any feedback is welcome: https://repo.almalinux.org/almalinux/8/cloud/x86_64/images/

**Comment by mariusleu** [comment]
Thank you @ezamriy 
As a first feedback is that we also need a more stable release than the daily build, so that one can rely on a number like "8.4" instead of "20210616".
I am not sure how AlmaLinux is plannig the release train, but since this issue is closed we need a major release of this image, too.

**Comment by fbhdk** [comment]
It is not necessarily a problem, however, if trying to cleanly migrate from CentOS, then `net.ifnames=0` should not be set as boot option (https://github.com/AlmaLinux/cloud-images/blob/master/http/almalinux-8.gencloud.ks) 

It causes the network interface to be named eth0 under KVM rather than ens3. In my case, where I simply tried to replace the qcow2 I made manually with this one, it failed to come online because my `meta-data` file for cloud-init contains interface name. 

In terms of naming - I have no problem with that, as it is also how CentOS names it and people should be used to that. 

However, if one wanted to do something nice it would be to build the image regularly and symlink it from e.g. `AlmaLinux-8-GenericCloud-latest.x86_64.qcow2` so that the `dnf update` when rolling a new vm does not take that long.

**Comment by hohl** [comment]
> @ AlmaLinux team:
> Any feedback is welcome: https://repo.almalinux.org/almalinux/8/cloud/x86_64/images/

Thanks for the work put into this!

> @fbhdk:
> It is not necessarily a problem, however, if trying to cleanly migrate from CentOS, then `net.ifnames=0` should not be set as boot option (https://github.com/AlmaLinux/cloud-images/blob/master/http/almalinux-8.gencloud.ks)

Setting it to 0 disables the predictable naming feature (see [docs](https://man7.org/linux/man-pages/man8/systemd-udevd.service.8.html)). The difference between `eth0` and `ens3` thus likely originates from somewhere else, as CentOS also has it disabled in all their images as far as I remember.

**Comment by fbhdk** [comment]
> Setting it to 0 disables the predictable naming feature (see [docs](https://man7.org/linux/man-pages/man8/systemd-udevd.service.8.html)). The difference between `eth0` and `ens3` thus likely originates from somewhere else, as CentOS also has it disabled in all their images as far as I remember.

You are absolutely right, it is my mistake, I looked at the wrong line when comparing.   Please disregard my comment about interface naming.

**Comment by ezamriy** [comment]
Yeah, my goal was creating an image that will be as close to the CentOS one as possible so that people can use it as a drop-in replacement.
The question is only about tooling: at the end I see it as a minimal necessary kickstart file and a set of well documented and tested Ansible roles so that it can be easily used for producing derivatives. Of course it will take some time for refactoring, improving CI and arranging other things.

**Comment by ezamriy** [comment]
@mariusleu 

> As a first feedback is that we also need a more stable release than the daily build, so that one can rely on a number like "8.4" instead of "20210616".

Let me explain the naming scheme, please:
```
AlmaLinux-8-GenericCloud-8.4-20210616.x86_64.qcow2

* AlmaLinux - distribution name
* 8 - major distribution version
* GenericCloud - image type
* 8.4 - minor distribution version. It will be changed to 8.5 and so on later
* 20210616 - image build timestamp
* x86_64 - architecture
* qcow2 - image format
```
It doesn't mean that this image is a daily or unstable build, but it clearly indicates when this image has been built and/or updated.

> I am not sure how AlmaLinux is plannig the release train, but since this issue is closed we need a major release of this image, too.

We are updating all our cloud/container images due to the following reasons:

- security updates available for the packages on an image
- fixed a bug reported by the community or our CI which is evolving constantly

Does it mean that such an update turns an image into something beta/unstable state? I don't think so! It just improves the quality and offers the community a secure image out of the box.

But if you are not okay with regularly updates (usually once per month), you can just hold on a specific image version. It's completely up to you :)

**Comment by ezamriy** [comment]
Btw, guys, I closed this GH issue because that milestone is achieved. But if you see any bugs/problems with the image, just create another issue and let's work on it.
