### ISSUE TITLE
VirtualBox: Unable to install Guest Additions on AlmaLinux OS 8.8

### ISSUE THREAD

**Issue by LKHN** [AlmaLinux/cloud-images#148]
See: https://www.virtualbox.org/ticket/21690

VirtualBox version is `7.0.8`

**Comment by vchepkov** [comment]
Could you, please, release vagrant images for AlmaLinux 8.8?

**Comment by LKHN** [comment]
@vchepkov Hi, Unfortunatelly, the Guest Additions still broken for AlmaLinux OS 8.8. As you can see from the latest response of developer, we are waiting for her/him to have AlmaLinux OS 8.8 VM and reproduce the issue.

**Comment by LKHN** [comment]
@vchepkov , We just released the first version of AlmaLinux OS 8.8 Vagrant box for VirtualBox provider with https://www.virtualbox.org/download/testcase/VBoxGuestAdditions_7.0.9-158050.iso to include Enterprise Linux 8.8 support. Everything works as expected so far, Please, let me know if you catch anything interesting.

See: https://app.vagrantup.com/almalinux/boxes/8/versions/8.8.20230606

**Comment by vchepkov** [comment]
@LKHN , just updated the box, everything works as expected, thank you!

**Comment by LKHN** [comment]
@vchepkov Thanks for the feedback! I will close this issue once the new stable version of VirtualBox released with the fixes.

**Comment by Betti2317** [comment]
➜  kube-demo2 vagrant up                           
Bringing machine 'default' up with 'parallels' provider...
==> default: Box 'almalinux/9.aarch64' could not be found. Attempting to find and install...
    default: Box Provider: parallels
    default: Box Version: >= 0
==> default: Loading metadata for box 'almalinux/9.aarch64'
    default: URL: https://vagrantcloud.com/almalinux/9.aarch64
==> default: Adding box 'almalinux/9.aarch64' (v9.2.20230717) for provider: parallels
    default: Downloading: https://vagrantcloud.com/almalinux/boxes/9.aarch64/versions/9.2.20230717/providers/parallels.box
==> default: Successfully added box 'almalinux/9.aarch64' (v9.2.20230717) for 'parallels'!
==> default: Registering VM image from the base box 'almalinux/9.aarch64'...
==> default: Creating new virtual machine as a linked clone of the box image...
==> default: Unregistering the box VM image...
==> default: Setting the default configuration for VM...
==> default: Checking if box 'almalinux/9.aarch64' version '9.2.20230717' is up to date...
==> default: Setting the name of the VM: kube-demo2_default_1691573550481_71634
==> default: Preparing network interfaces based on configuration...
    default: Adapter 0: shared
==> default: Clearing any previously set network interfaces...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 10.211.55.8:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for Parallels Tools installed on the VM...
==> default: Parallels Tools were not detected on this VM! They are required
==> default: for shared folders, time sync and more. If shared folders are not
==> default: working on this machine, please install Parallels Tools within the
==> default: virtual machine and reload your VM.
==> default: Mounting shared folders...
    default: /vagrant => /Users/venus/Vagrant/kube-demo2
Vagrant was unable to mount Parallels Desktop shared folders. This is usually
because the filesystem "prl_fs" is not available. This filesystem is
made available via the Parallels Tools and kernel module.
Please verify that these guest tools are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t prl_fs -o uid=1000,gid=1000,_netdev vagrant /vagrant

The error output from the command was:

mount: /vagrant: unknown filesystem type 'prl_fs'.
