### ISSUE TITLE
Community AMI

### ISSUE THREAD

**Issue by krionbsd** [AlmaLinux/cloud-images#15]
So far only marketplace AMI is available, any plans to provide community AMI soon?

**Comment by jaboutboul** [comment]
Hey @krionbsd. Thanks for asking. The Marketplace AMI is totally free and we don’t charge for any subscription or anything like RHEL, which releases the community AMI so that you can bring your own, so just wondering what the benefit of community AMI would be? Not against, just wondering what people think.

**Comment by krionbsd** [comment]
@jaboutboul thanks for feedback, you can't reshare marketplace AMIs, we're using them for [Salt Project](https://saltproject.io/) CI

**Comment by ezamriy** [comment]
hi @krionbsd.

I've uploaded our AMI's to all regions and listed them here: https://wiki.almalinux.org/cloud/AWS.html
The same information is exported into that CSV file for CI purposes: https://wiki.almalinux.org/ci-data/aws_amis.csv

Let me know, please, does it fit your needs?

**Comment by krionbsd** [comment]
Thanks guys, it seems it works :)
