### ISSUE TITLE
Add LXC Template

### ISSUE THREAD

**Issue by liberodark** [AlmaLinux/cloud-images#8]
Hi,

You can add LXC template in https://us.images.linuxcontainers.org/
This files can help you : 
[CentOS 8.zip](https://github.com/AlmaLinux/cloud-images/files/6235069/CentOS.8.zip)
You can build with https://linuxcontainers.org/distrobuilder/introduction/

Best Regards

**Comment by dejlek** [comment]
I would also welcome being able to launch AlmaLinux containers (LXC)...

**Comment by kotakomputer** [comment]
Hope AlmaLinux available for LXC soon. Any estimated time?

**Comment by ezamriy** [comment]
One of the community members is working on that, we hope to have it done soon.

**Comment by ezamriy** [comment]
@liberodark @dejlek @kotakomputer hi!

I'm happy to report that we have some progress with this:

* We prepared an AlmaLinux support patch for the [distrobuilder](https://github.com/lxc/distrobuilder) tool, you can find the patched version here: https://github.com/AlmaLinux/distrobuilder
* We prepared a configuration file for the distrobuilder, it can be found here: https://github.com/AlmaLinux/lxc-ci/blob/master/images/almalinux.yaml

After [compiling](https://github.com/AlmaLinux/distrobuilder#installing-from-source) a patched distrobuilder version you will be able to build an LXC image using the following command:

```bash
$ distrobuilder build-lxc almalinux.yaml
```

and an LXD image with the following command:

```bash
$ distrobuilder build-lxd almalinux.yaml
```

I've checked the LXC image and it seems to be working pretty fine.

It would be really great if you, guys, can test it and provide some feedback.

Also, if someone who reads this knows to Go, please help us review/polish this code https://github.com/AlmaLinux/distrobuilder/blob/master/sources/almalinux-http.go a bit so that we can try submitting it to upstream.

Our next actions will be:

- collect feedback from the community and perform additional testing
- polish our patch for distrobuilder
- submit PRs with our modifications to upstream
- images will become publicly available when LXC devs add it to their CI pipeline

**Comment by alitvak69** [comment]
``` 
# sudo ../go/bin/distrobuilder build-lxc almalinux.yaml 
Error: source.downloader must be one of [alpinelinux-http alt-http apertis-http archlinux-http centos-http debootstrap fedora-http gentoo-http ubuntu-http sabayon-http docker-http oraclelinux-http opensuse-http openwrt-http plamolinux-http voidlinux-http funtoo-http]
```

**Comment by alitvak69** [comment]
I had to pull code from AlmaLinux fork instead of lxc master.

**Comment by alitvak69** [comment]
It worked for me I installed it in proxmox 6.4.  What is the meta file for?

**Comment by liberodark** [comment]
How to build : 

```
go get -d -v github.com/AlmaLinux/distrobuilder/distrobuilder
cd $HOME/go/src/github.com/AlmaLinux/distrobuilder
make
cd
mkdir -p $HOME/ContainerImages/AlmaLinux/
cd $HOME/ContainerImages/AlmaLinux/
wget https://raw.githubusercontent.com/AlmaLinux/lxc-ci/master/images/almalinux.yaml
sudo $HOME/go/bin/distrobuilder build-lxc almalinux.yaml
```

Best Regards

**Comment by liberodark** [comment]
Good work @ezamriy you have upstream your work only need lxc-ci now :D

**Comment by taidos** [comment]
I made it work and i tested myself

**Comment by ezamriy** [comment]
Prepared 2 more PRs for LXC:

* https://github.com/lxc/lxc-ci/pull/305
* https://github.com/lxc/distrobuilder/pull/449

Let's wait for approval and officially built images before closing this issue.

**Comment by ezamriy** [comment]
AlmaLinux OS LXC/LXD images are available from https://images.linuxcontainers.org/ now.

Thanks to everyone helping with it. I'm closing this issue.
