### ISSUE TITLE
SSH authentication doesn't work on aarch64 AWS instances

### ISSUE THREAD

**Issue by der-eismann** [AlmaLinux/cloud-images#80]
While setting up a new instance on AWS I noticed that the SSH authentication with public keys doesn't seem to work on the aarch64 instances.

Creating a `t3a.nano` instance in `eu-west-1` with `ami-0bff8ab282778f447` works fine, either by providing an SSH key or using the `user data` setup. 

Creating a `t4g.nano` instance in `eu-west-1` with `ami-00e168d283ea84df3` however doesn't - all I get is 
```
ec2-user@12.34.56.78: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

However I can't seem to debug it because AWS doesn't provide screenshots on ARM instances. Can somebody confirm or fix this issue?

**Comment by LKHN** [comment]
Hey Philipp,

Since `2GB` is the minimum requirement for the `aarch64`[^1]. Cloud-init crashes while creating the "Cloud User" (`ec2-user`) with the `0.5GB` RAM on `t4g.nano`.

You can use the `Amazon SSM Agent` to connect instances without SSH. It is installed and enabled in the AMI.
I never faced any issue with the `t4g.micro` (`1GB RAM`). So we could say that you need at least `1GB RAM` instance type to use the AlmaLinux AMI.

Thanks for the report! :+1: 

[^1]: https://access.redhat.com/articles/rhel-limits#minimum-required-memory-3
