### ISSUE TITLE
Request to reduce image size

### ISSUE THREAD

**Issue by JASKevinWhite** [AlmaLinux/cloud-images#85]
I have used the Alma 8 AWS EC2 images, which are 10GB in size.  (I don't know if Alma 9 is different, or if images on different platforms are different).  When you launch an instance from an image, you can make the volume larger than the image's volume size, but you can't make it smaller.  Since Alma's images are 10GB, that means I can't make an image smaller than 10GB.  For example, however, Fedora's are 6GB.  Both are actually far larger than the base install actually is (for which 2GB would be plenty).  I suspect that the cloud image stuff originally comes from upstream, and I'm not sure how much Alma wants to deviate from that, but would it be possible to make the Alma AMI images smaller?  Maybe the 6GB size that Fedora uses?  

This may not seem like a big deal, but we fire up a fairly large number of instances, and most of that space goes to waste, which is just extra cost.  I know that a smaller image size may not be useful for many uses, but making your instance larger than the AMI size upon launch is trivial.

**Comment by LKHN** [comment]
Hey Kevin!

Thanks for your feedback and help in making AlmaLinux OS AMIs better.
I've done some tests. I think reducing the disk size reduces overall build time too. Since disk usages are `1.2GiB(x86_64)` and `1.4GiB(aarch64)`, We want to release 8.6 AMIs with `4GiB` for both architectures. IMHO, the `2.9GiB(x86_64)` and `2.1GiB(aarch64)` free space should be enough for many use cases. I think it would better technical practise and cost-effective to customize disk properties instead of relying on the default size. Let's see how it goes with the remaining AMI users.

**Comment by JASKevinWhite** [comment]
Thanks for including this!  This will help me a great deal!  Hopefully it will be helpful for others as well.

**Comment by LKHN** [comment]
Kevin,

Many thanks too you!

The `9.0 Beta 1` AMIs also are available with `4GiB` root disk size from the community channel: https://wiki.almalinux.org/cloud/AWS.html

Enjoy, and feel free to close the issue, continue to discuss and/or open a new one.
